---
swagger: "2.0"
info:
  version: "1.0"
  title: "LineScrape"
host: "api.seanfischer.io"
basePath: "/v0"
schemes:
- "https"
paths:
  /game-lines:
    get:
      parameters:
      - name: "league"
        in: "query"
        description: "The sport league to pull lines for. Currently there are 4 leagues\
          \ supported, NFL, NBA, college-football, and college-basketball."
        required: true
        type: "string"
      - name: "source"
        in: "query"
        description: "The sports book to pull lines from. mybookie.ag (mybookie) and\
          \ Caesars (caesars) are supported."
        required: true
        type: "string"
      responses: {}
      security:
      - api_key: []
  /game-projections:
    get:
      parameters:
      - name: "gameDate"
        in: "query"
        required: true
        type: "string"
      - name: "source"
        in: "query"
        required: true
        type: "string"
      responses: {}
      security:
      - api_key: []
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "x-api-key"
    in: "header"
