AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Collect and compile data related to sports line odds and win projections

Globals:
  Function:
    Timeout: 15

Resources:
  UpdateLinesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cmd/lambda/update-lines
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Policies: arn:aws:iam::261392311630:policy/DynamoDBReadWriteGameOdds
      Events:

        # BASKETBALL -----------------------------------------------
        MybookieNCAAB:
          Type: Schedule
          Properties:
            Enabled: True
            Schedule: 'rate(5 minutes)'
            Input: '{"Source": "mybookie", "League":"college-basketball"}'
        MybookieNBA:
          Type: Schedule
          Properties:
            Enabled: True
            Schedule: 'rate(5 minutes)'
            Input: '{"Source": "mybookie", "League":"NBA"}'
        CaesarsNCAAB:
          Type: Schedule
          Properties:
            Enabled: True
            Schedule: 'rate(5 minutes)'
            Input: '{"Source": "caesars", "League":"college-basketball"}'
        CaesarsNBA:
          Type: Schedule
          Properties:
            Enabled: True
            Schedule: 'rate(5 minutes)'
            Input: '{"Source": "caesars", "League":"NBA"}'

        # FOOTBALL -----------------------------------------------
        MybookieCFB:
          Type: Schedule
          Properties:
            Enabled: False
            Schedule: 'rate(5 minutes)'
            Input: '{"Source": "mybookie", "League":"college-football"}'
        MybookieNFL:
          Type: Schedule
          Properties:
            Enabled: False
            Schedule: 'rate(5 minutes)'
            Input: '{"Source": "mybookie", "League":"NFL"}'
        CaesarsCFB:
          Type: Schedule
          Properties:
            Enabled: False
            Schedule: 'rate(5 minutes)'
            Input: '{"Source": "caesars", "League":"college-football"}'
        CaesarsNFL:
          Type: Schedule
          Properties:
            Enabled: False
            Schedule: 'rate(5 minutes)'
            Input: '{"Source": "caesars", "League":"NFL"}'

        # BASEBALL -----------------------------------------------
        MybookieMLB:
          Type: Schedule
          Properties:
            Enabled: True
            Schedule: 'rate(5 minutes)'
            Input: '{"Source": "mybookie", "League":"mlb"}'
        CaesarsMLB:
          Type: Schedule
          Properties:
            Enabled: True
            Schedule: 'rate(5 minutes)'
            Input: '{"Source": "caesars", "League":"mlb"}'

  UpdateEloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cmd/lambda/update-elo
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Policies:
        #- arn:aws:iam::261392311630:policy/S3GameOddsWriteOnly
        - arn:aws:iam::261392311630:policy/DynamoWriteWinProjections
      Environment:
        Variables:
          ProjectionsTableName: !GetAtt WinProjectionsTable.Arn
      Events:
        EachMorning:
          Type: Schedule
          Properties:
            Enabled: True
            Schedule: 'cron(0 10 * * ? *)'

  FetchLinesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cmd/lambda/fetch-lines
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Policies: arn:aws:iam::aws:policy/AmazonDynamoDBReadOnlyAccess
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /game-lines
            Method: get
            RestApiId:
              Ref: APIEndpoint

  FetchProjectionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cmd/lambda/fetch-projections
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Policies: arn:aws:iam::aws:policy/AmazonDynamoDBReadOnlyAccess
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /game-projections
            Method: get
            RestApiId:
              Ref: APIEndpoint

  APIEndpoint:
    Type: AWS::Serverless::Api
    DefinitionUri:
      Bucket: linescape-api
      Key: LineScrapeAPIv1.yaml
    Properties:
      StageName: v0

  GameOddsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: game-odds
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        -
          AttributeName: league
          AttributeType: S
        -
          AttributeName: time_stamp
          AttributeType: S
      KeySchema:
        -
          AttributeName: league
          KeyType: HASH
        -
          AttributeName: time_stamp
          KeyType: RANGE

  WinProjectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: win-projections
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        -
          AttributeName: gameId
          AttributeType: S
        -
          AttributeName: source
          AttributeType: S
        -
          AttributeName: gameDate
          AttributeType: S
      KeySchema:
        -
          AttributeName: gameId
          KeyType: HASH
        -
          AttributeName: source
          KeyType: RANGE
      GlobalSecondaryIndexes:
        -
          IndexName: ByDate
          KeySchema:
            -
              AttributeName: source
              KeyType: HASH
            -
              AttributeName: gameDate
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
