package game

// 538 shorthand to common names
var FteToCommon = map[string]string{
	"ARI": "Arizona Cardinals",
	"ATL": "Atlanta Falcons",
	"BAL": "Baltimore Ravens",
	"BUF": "Buffalo Bills",
	"CAR": "Carolina Panthers",
	"CHI": "Chicago Bears",
	"CIN": "Cincinnati Bengals",
	"CLE": "Cleveland Browns",
	"DAL": "Dallas Cowboys",
	"DEN": "Denver Broncos",
	"DET": "Detroit Lions",
	"GB":  "Green Bay Packers",
	"HOU": "Houston Texans",
	"IND": "Indianapolis Colts",
	"JAX": "Jacksonville Jaguars",
	"KC":  "Kansas City Chiefs",
	"LAC": "Los Angeles Chargers",
	"LAR": "Los Angeles Rams",
	"MIA": "Miami Dolphins",
	"MIN": "Minnesota Vikings",
	"NE":  "New England Patriots",
	"NO":  "New Orleans Saints",
	"NYG": "New York Giants",
	"NYJ": "New York Jets",
	"OAK": "Las Vegas Raiders",
	"PHI": "Philadelphia Eagles",
	"PIT": "Pittsburgh Steelers",
	"SEA": "Seattle Seahawks",
	"SF":  "San Francisco 49ers",
	"TB":  "Tampa Bay Buccaneers",
	"TEN": "Tennessee Titans",
	"WSH": "Washington Football Team",
}

var CommonToFte = map[string]string{
	"Arizona Cardinals":        "ARI",
	"Atlanta Falcons":          "ATL",
	"Baltimore Ravens":         "BAL",
	"Buffalo Bills":            "BUF",
	"Carolina Panthers":        "CAR",
	"Chicago Bears":            "CHI",
	"Cincinnati Bengals":       "CIN",
	"Cleveland Browns":         "CLE",
	"Dallas Cowboys":           "DAL",
	"Denver Broncos":           "DEN",
	"Detroit Lions":            "DET",
	"Green Bay Packers":        "GB",
	"Houston Texans":           "HOU",
	"Indianapolis Colts":       "IND",
	"Jacksonville Jaguars":     "JAX",
	"Kansas City Chiefs":       "KC",
	"Los Angeles Chargers":     "LAC",
	"Los Angeles Rams":         "LAR",
	"Miami Dolphins":           "MIA",
	"Minnesota Vikings":        "MIN",
	"New England Patriots":     "NE",
	"New Orleans Saints":       "NO",
	"New York Giants":          "NYG",
	"New York Jets":            "NYJ",
	"Las Vegas Raiders":        "OAK",
	"Philadelphia Eagles":      "PHI",
	"Pittsburgh Steelers":      "PIT",
	"Seattle Seahawks":         "SEA",
	"San Francisco 49ers":      "SF",
	"Tampa Bay Buccaneers":     "TB",
	"Tennessee Titans":         "TEN",
	"Washington Football Team": "WSH",
}
